const ROUTES = {
  START_SCREEN: "START_SCREEN",
  CHOOSE_RULESET: "CHOOSE_RULESET",
  CHOOSE_FACTION: "CHOOSE_FACTION",
  ADD_UNITS_ZERO_STATE: "ADD_UNITS_ZERO_STATE",
  ADD_UNITS: "ADD_UNITS",
};

export const INITIAL_ROUTE = ROUTES.START_SCREEN;

export default ROUTES;
